<?php
/**
 * BS_Crypto extension
 * 
 * @category       BS
 * @package        BS_Crypto
 * @copyright      Copyright (c) 2018
 */
/**
 * Investment view widget template
 *
 * @category    BS
 * @package     BS_Crypto
 * @author Bui Phong
 */
?>
<?php $_investment = $this->getCurrentInvestment();?>
<?php if ($_investment) :?>
    <div class="investment-widget-view">
        <h3><?php echo $_investment->getName()?></h3>
        <div>
            <div class="name-widget">
                <?php echo Mage::helper('bs_crypto')->__('Name');?>:<?php echo $_investment->getName();?>
            </div>
            <div class="init_value-widget">
                <?php echo Mage::helper('bs_crypto')->__('Investment Value');?>:<?php echo $_investment->getInitValue();?>
            </div>
            <div class="customer_id-widget">
                <?php echo Mage::helper('bs_crypto')->__('Customer');?>:<?php echo $_investment->getCustomerId();?>
            </div>

        </div>
    </div>
<?php endif;?>
